In [2]:
import numpy as np
import sklearn.datasets as ds
import numpy as np
large_array, _ = ds.make_gaussian_quantiles(n_samples=10000, n_features=1, random_state=42)
large_array= large_array.reshape((10000,))
a = np.array(ds.load_iris().data)


## 1. Efficiency of numpy operations
large_array is generated with dummy data. You do not have to understand how it's done.

a. Check the dtype and shape of `large_array`

In [3]:
#SOLUTION_START
print(f'The shape of large_array is {large_array.shape} and its dtype is {large_array.dtype}')
#SOLUTION_END

The shape of large_array is (10000,) and its dtype is float64


b. Create a for-loop in which you calculate the power of 2 for each element. `%%timeit` is  placed at the beginning of the cell. By doing this, Jupiter will do several runs and measure the speed of the operation. The result is shown below the cell. Run the cell and wait for the result. Look how long running the for-loop takes.

In [7]:
%%timeit
#SOLUTION_START
large_array**2
#SOLUTION_END

1.6 μs ± 41.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


c. In the cell below, do the same with the Ufuncs functionality instead of a for-loop. Use %%timeit again. Compare the duration. How big is the difference?

In [5]:
%%timeit
#SOLUTION_START
for e in large_array:
    e**2
#SOLUTION_END

772 μs ± 4.13 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


<div style="border: 2px solid red; padding: 10px; border-radius: 5px; background-color: #f8d7da; color: #721c24;">
<strong>! </strong>As you can see for yourself there is a big difference.
From now on, where possible, you have to use UFuncs instead of for-loops. The code is more lean and will be excecuted more efficiently. During evaluations for-loops will influence your score negatively and are even not allowed in most cases..</div>


## 2. Using UFuncs
Use UFuncs to perform the following operations on array a. This array contains features of the iris dataset\
a. From array a, multiply every element by 2\
b. From array a, calculate the square root of each element.\
c. From array a, round the first column to the nearest integer.\
d. From array a, add 1 to every value of the first row.


In [8]:
#SOLUTION_START
print(f'a. Every element multiplied by 2\n {a * 2}')
#For simple arithmetic you can just use Pythons operators. Numpy will transform this to np.multiply(a,2).Numpy will perform the vector-based calculations
print(f'a. Every element multiplied by 2\n {np.multiply(a, 2)}')
#So the two calculations above do exactly the same.
print(f'a. The square root of each element in a is {np.sqrt(a)}')
print(f'b. The first column rounded to the nearest integer is {np.round(a[:,0])}')
print(f'd. The first row with 1 added to every element is {a[0,:]+1}')
#SOLUTION_END

a. Every element multiplied by 2
 [[10.2  7.   2.8  0.4]
 [ 9.8  6.   2.8  0.4]
 [ 9.4  6.4  2.6  0.4]
 [ 9.2  6.2  3.   0.4]
 [10.   7.2  2.8  0.4]
 [10.8  7.8  3.4  0.8]
 [ 9.2  6.8  2.8  0.6]
 [10.   6.8  3.   0.4]
 [ 8.8  5.8  2.8  0.4]
 [ 9.8  6.2  3.   0.2]
 [10.8  7.4  3.   0.4]
 [ 9.6  6.8  3.2  0.4]
 [ 9.6  6.   2.8  0.2]
 [ 8.6  6.   2.2  0.2]
 [11.6  8.   2.4  0.4]
 [11.4  8.8  3.   0.8]
 [10.8  7.8  2.6  0.8]
 [10.2  7.   2.8  0.6]
 [11.4  7.6  3.4  0.6]
 [10.2  7.6  3.   0.6]
 [10.8  6.8  3.4  0.4]
 [10.2  7.4  3.   0.8]
 [ 9.2  7.2  2.   0.4]
 [10.2  6.6  3.4  1. ]
 [ 9.6  6.8  3.8  0.4]
 [10.   6.   3.2  0.4]
 [10.   6.8  3.2  0.8]
 [10.4  7.   3.   0.4]
 [10.4  6.8  2.8  0.4]
 [ 9.4  6.4  3.2  0.4]
 [ 9.6  6.2  3.2  0.4]
 [10.8  6.8  3.   0.8]
 [10.4  8.2  3.   0.2]
 [11.   8.4  2.8  0.4]
 [ 9.8  6.2  3.   0.4]
 [10.   6.4  2.4  0.4]
 [11.   7.   2.6  0.4]
 [ 9.8  7.2  2.8  0.2]
 [ 8.8  6.   2.6  0.4]
 [10.2  6.8  3.   0.4]
 [10.   7.   2.6  0.6]
 [ 9.   4.6  2.6  0.6]
